# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\mac\Home\Desktop\myBots\capza-app\capza\views\select_probe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 20)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.horizontalFrame.setStyleSheet("color: #AEDC21;\n"
"background-color: #0C5C51;")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #AEDC21; background-color: transparent;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_2.setMaximumSize(QtCore.QSize(40, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logos/icon_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(30, 10, 30, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.probe_filter_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(11)
        self.probe_filter_lineedit.setFont(font)
        self.probe_filter_lineedit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    border: 1px solid #C7C7C7;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus {\n"
"    \n"
"    background-color: rgb(255, 253, 219);\n"
"    border: 1px solid black\n"
"}")
        self.probe_filter_lineedit.setMaxLength(20)
        self.probe_filter_lineedit.setClearButtonEnabled(True)
        self.probe_filter_lineedit.setObjectName("probe_filter_lineedit")
        self.horizontalLayout_2.addWidget(self.probe_filter_lineedit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.results_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(11)
        self.results_lbl.setFont(font)
        self.results_lbl.setObjectName("results_lbl")
        self.horizontalLayout_2.addWidget(self.results_lbl)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        self.tableView.setFont(font)
        self.tableView.setStyleSheet("background: #FCFCFC;border-radius: 10px;margin-left:20px; margin-right:20px;\n"
"")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setMinimumSectionSize(400)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(True)
        self.tableView.verticalHeader().setCascadingSectionResizes(True)
        self.tableView.verticalHeader().setDefaultSectionSize(24)
        self.verticalLayout.addWidget(self.tableView)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("background-color: white;\n"
"border: 1px solid red;\n"
"border-radius: 10px;\n"
"text-align:center;\n"
"margin-left: 50px;\n"
"margin-right: 50px;")
        self.cancel_btn.setObjectName("cancel_btn")
        self.verticalLayout.addWidget(self.cancel_btn)
        self.load_probe_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_probe_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.load_probe_btn.setFont(font)
        self.load_probe_btn.setStyleSheet("background-color: #AEDC21;\n"
"border-radius: 10px;\n"
"text-align:center;\n"
"margin-left: 50px;\n"
"margin-right: 50px;")
        self.load_probe_btn.setObjectName("load_probe_btn")
        self.verticalLayout.addWidget(self.load_probe_btn)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Laborauswertung:"))
        self.label_3.setText(_translate("MainWindow", "Suche nach Kennung:"))
        self.probe_filter_lineedit.setPlaceholderText(_translate("MainWindow", "ENE XXXX"))
        self.results_lbl.setText(_translate("MainWindow", "XXXX Ergebnisse gefunden"))
        self.cancel_btn.setText(_translate("MainWindow", "Abbrechen"))
        self.load_probe_btn.setText(_translate("MainWindow", "Lade Probe"))
import icons_rc
